server:
  port: 4000
  
spring:
  application:
    name: GatewayMS
  cloud:
    consul: 
      host: localhost
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: PostsMS
          uri: lb://PostsMS
          predicates:
          - Path=/posts/**
        - id: UserMS
          uri: lb://UserMS
          predicates:
          - Path=/users/**
        - id: FriendMS
          uri: lb://FriendMS
          predicates:
          - Path=/friends/**
        - id: FriendRequestMS
          uri: lb://FriendRequestMS
          predicates:
          - Path=/requests/**
        - id: DataMS
          uri: lb://DataMS
          predicates:
          - Path=/data/**